GET http://localhost:3000/studentatt1/?department=agri&semester=II
Content-Type: application/json
###
GET http://localhost:3000/sample
###


### Search for students in a department (example: CSE) with query 'john'
GET http://localhost:3000/studentsearch/agri?q=kumar


####

PUT http://localhost:3000/studentdet/23AG001
Content-Type: application/json

{
  "Name": "Kumar",
  "Reg_Number": "23AG001",
  "Address": "Salem",
  "Mobile": "9876543210",
  "Father_Mobile": "9123456789"
}

####
POST http://localhost:3000/addfaculty1
Content-Type: application/json

{
  "Department": "CSE",
  "Staff_Code": "12345",
  "joiningDate": "2023-06-01",
  "Staff_Name": "Dr. Ramesh",
  "photo": "ramesh.jpg",
  "E_Mail": "ramesh@college.edu",
  "Mobile": "9876543210",
  "Designation": "Assistant Professor",
  "roleofwork": "Teaching",
  "qualification": "PhD",
  "university": "Anna University",
  "Experience_Year": "5",
  "Status1": "Active",
  "officeAddress": "Room 205, Block B",
  "officeHours": "9 AM - 4 PM"
}
### Get Student Attendance Details
GET http://localhost:3000/attendanceup/?department=agri&semester=II


### Search Faculty by Name and Department
GET http://localhost:3000/searchUsers?search=ram&department=agri

####
GET http://localhost:3000/par-cgpaatt-data/22AG003

### Get hostelers absent today from department (eg: CSE)
GET http://localhost:3000/wadernlogin

### Get students with CGPA <= 5 from a specific department
GET http://localhost:3000/dashattdet/agri

####
### Get students with CGPA <= 5 from a specific department

GET http://localhost:3000/allhosteldata
#####
GET http://localhost:3000/department/agri

### Get students with CGPA <= 5 from a specific department
http://localhost:3000/studentatt1?department=agri&semester=II

### Get students with CGPA <= 5 from a specific department
GET http://localhost:3000/excellentstudentacadamicdet/agri



### Get hostel data from nri1 table
GET http://localhost:3000/allhostelleavedata/nri2
Content-Type: application/json

###

### Get hostel data from nri2 table
GET http://localhost:3000/hosteldat/nri2
Content-Type: application/json

###
GET http://localhost:3000/attendanceup/?department=AGRI &semester=II HTTP/1.1

### Get hostel data from nri3 table
GET http://localhost:3000/hosteldat/nri3
Content-Type: application/json

###
GET http://localhost:3000/api/teacher-attendance-summary HTTP/1.1
Content-Type: application/json

### Get hostel data from nri4 table
GET http://localhost:3000/hosteldat/nri4
Content-Type: application/json


######
POST http://localhost:3000/parentlogin
Content-Type: application/json

{
  "regno": "23cs092",
  "Password": "12345"
}
###
GET http://localhost:3000/api/teacher-daily-status/dept?department=CSE


GET http://localhost:3000/api/semester-dat/22AG003?semester=I

### Get Semester Data by Registration Number
GET http://localhost:3000/api/incidents/23IT120 HTTP/1.1
Content-Type: application/json

#######
GET http://localhost:3000/api/incidents/23cs092

GET http://localhost:3000/api/children/22AG003 HTTP/1.1
Content-Type: application/json
###
GET http://localhost:3000/api/subdata/22AG003?semester=I

####
GET http://localhost:3000/api/siblingdata/23cs092

### Get student day-wise attendance
GET http://localhost:3000/studentdaywise1/23CS065/2025-02-21


### Get student rank by regno
GET http://localhost:3000/api/teacher-daily-status

####

GET http://localhost:3000/api/teacher-daily-summary/2025-04-28 HTTP/1.1
Content-Type: application/json


####
GET http://localhost:3000/api/teacher-daily-summary1/2025-04-30?mobile=9095627270



#####
GET http://localhost:3000/api/teacher-status/CSE
Accept: application/json

 GET http://localhost:3000/api/teacher-daily-status


####
### Assign work to all staff
POST http://localhost:3000/work/assign
Content-Type: application/json

{
  "assignBy": "shankar",
  "workDetails": "Prepare lab setup",
  "targetDate": "2025-04-11",
  "assignedTo": "all"
}

####
POST http://localhost:3000/work/assign
Content-Type: application/json

{
  "assignBy": "Admin",
  "workDetails": "Update course file",
  "targetDate": "2025-05-10",
  "assignedTo": "all",
  "department": "agri"
}



#####
POST http://localhost:3000/work/assign
Content-Type: application/json

{
  "assignBy": "Principal",
  "workDetails": "Prepare lab manuals",
  "targetDate": "2025-05-10",
  "assignedTo": "all"
}



######
POST http://localhost:3000/work/assign
Content-Type: application/json

{
  "assignBy": "Admin",
  "statusSelect": "Pending",
  "workDetails": "Prepare semester report",
  "targetDate": "2025-05-10",
  "assignedTo": "9524642654",
  "dept": "agri"
}
